---
- hosts: "{{ target | default('10.210.35.200') }}"
  connection: httpapi
  collections:
    - fortinet.fortimanager
  vars_files:
    - global_variables.yml
    
  tasks:
    - name: Load CSV file {{ firewall_address_csv_file | basename() }}
      community.general.read_csv:
        path: '{{ firewall_address_csv_file }}' 
        fieldnames: name,subnet,color,comment
        delimiter: ';'
      register: firewall_addresses
      delegate_to: localhost

    - name: Show CSV-collected firewall addresses
      debug:
        msg: "{{ firewall_addresses }}"

    - name: Add firewall addresses in FortiManager
      include_tasks: tasks/fmg_add_firewall_address.yml
      #loop: [ adom1, adom2 ]
      loop: [adom1]
      loop_control:
        loop_var: adom
