---
- name: Add firewall addresses in ADOM "{{ adom }}"
  fmgr_firewall_address:
    adom: '{{ adom }}'
    state: "{{ action | default('present') }}"
    firewall_address:
      name: '{{ item.name }}'
      subnet: '{{ item.subnet }}'
      color: '{{ item.color }}'
      comment: '{{ item.comment }}'
  loop: '{{ firewall_addresses.list }}'
